In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv('datasets\heart.csv')


<>:4: SyntaxWarning: invalid escape sequence '\h'
<>:4: SyntaxWarning: invalid escape sequence '\h'
C:\Users\kelvi\AppData\Local\Temp\ipykernel_21500\2650624505.py:4: SyntaxWarning: invalid escape sequence '\h'
  df=pd.read_csv('datasets\heart.csv')


In [31]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [32]:
from sklearn.preprocessing import StandardScaler
sl = StandardScaler()
for i in ['age','cigsPerDay','prevalentStroke','prevalentHyp','diabetes']:
    df[i] = sl.fit_transform(df[i].values.reshape(-1,1))
df.head()

male       age  education  currentSmoker  cigsPerDay  BPMeds  \
0     1 -1.234951        4.0              0   -0.755376     0.0   
1     0 -0.418257        2.0              0   -0.755376     0.0   
2     1 -0.184916        1.0              1    0.922662     0.0   
3     0  1.331800        3.0              1    1.761681     0.0   
4     0 -0.418257        3.0              1    1.174368     0.0   

   prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0        -0.077033     -0.671101 -0.162477    195.0  106.0   70.0  26.97   
1        -0.077033     -0.671101 -0.162477    250.0  121.0   81.0  28.73   
2        -0.077033     -0.671101 -0.162477    245.0  127.5   80.0  25.34   
3        -0.077033      1.490089 -0.162477    225.0  150.0   95.0  28.58   
4        -0.077033     -0.671101 -0.162477    285.0  130.0   84.0  23.10   

   heartRate  glucose  TenYearCHD  
0       80.0     77.0           0  
1       95.0     76.0           0  
2       75.0     70.0           0  
3       65.0    103.0           1  
4       85.0     85.0           0

In [33]:
df=df.dropna()

In [34]:
x=df.drop(columns=['TenYearCHD','education','BPMeds'])
y=df['TenYearCHD']

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_recall_curve,precision_score,roc_curve 
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)

c:\Users\kelvi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [37]:
accuracy_score_test = accuracy_score(y_test,y_pred)
print("Accuracy on test set:", accuracy_score_test)

Accuracy on test set: 0.8538251366120219


In [38]:
y_pred_train = lr.predict(x_train)
accuracy_score_train = accuracy_score(y_train,y_pred_train)
print("Accuracy on train set:", accuracy_score_train)

Accuracy on train set: 0.8491792065663475


In [40]:
confusion_matrix(y_test,y_pred)


array([[619,   4],
       [103,   6]], dtype=int64)

In [41]:
precision_recall_curve= precision_recall_curve(y_test,y_pred)

In [42]:
precision_recall_curve

(array([0.1489071, 0.6      , 1.       ]),
 array([1.        , 0.05504587, 0.        ]),
 array([0, 1], dtype=int64))